### ISSUE TITLE
Two incorrect Chicago matches included in list of matches

### ISSUE THREAD

**Issue by agale123** [nwslR/nwslR#10]
It looks like the list of matches contains two extra matches that probably were old dates for rescheduled ones. Here are the incorrect ones that need to be deleted:

`chicago-red-stars-vs-north-carolina-courage-2023-06-09` (correct match is `chicago-red-stars-vs-north-carolina-courage-2023-06-10`)

`angel-city-fc-vs-chicago-red-stars-2023-06-04` (correct match is `angel-city-fc-vs-chicago-red-stars-2023-06-05`)

**Comment by lvanden** [comment]
Data has been updated and I believe this has been resolved. When I run the following I only see one match for each of these games. 
```
load_matches() |>
    dplyr::filter(
        grepl("chicago-red-stars-vs-north-carolina-courage-2023-06", match_id) |
        grepl("angel-city-fc-vs-chicago-red-stars-2023-06", match_id)
    )
```
