### ISSUE TITLE
Player match stats returns team match stats for some 2023 matches

### ISSUE THREAD

**Issue by agale123** [nwslR/nwslR#8]
I was looking at all Reign games and these two player match summaries are returning team match summaries:

https://github.com/nwslR/nwsldata/releases/download/player_match_summaries/washington-spirit-vs-ol-reign-2023-03-26.csv
https://github.com/nwslR/nwsldata/releases/download/player_match_summaries/nj-ny-gotham-fc-vs-ol-reign-2023-04-01.csv

This probably impacts some other early season games, I was just looking at Reign games for now. I also hit a bunch of missing pre-2023 ones but I assume those are because the data is missing so I got what I needed from the NWSL website instead.

**Comment by akschmitt** [comment]
It looks like this is the case for the first 11 matches of 2023 (matches from 3/25-4/1)

**Comment by adror1** [comment]
Just seeing this now (for some reason I'm not getting issue notifications)...will work on this ASAP!

**Comment by adror1** [comment]
I think this is solved @agale123 and @akschmitt, let me know if it's still an issue?

**Comment by akschmitt** [comment]
It's fixed for me! Thanks so much :-)
