### ISSUE TITLE
ACFC v CRS 2023-06-05 data error

### ISSUE THREAD

**Issue by akschmitt** [nwslR/nwslR#9]
It seems like the player- and team-level individual match stats csvs for the ACFC vs Red Stars match 

(https://github.com/nwslR/nwsldata/releases/download/player_match_summaries/angel-city-fc-vs-chicago-red-stars-2023-06-04.csv and https://github.com/nwslR/nwsldata/releases/download/team_match_summaries/angel-city-fc-vs-chicago-red-stars-2023-06-04.csv) 

have duplicates of every analytic because they contain match_id's for "angel-city-fc-vs-chicago-red-stars-2023-06-04" and "angel-city-fc-vs-chicago-red-stars-2023-06-05", while there is no corresponding individual csv for angel-city-fc-vs-chicago-red-stars-2023-06-05, which has a valid match id when you call load_matches()

This returns an error indicating the match does not have data when calling load_player_match_stats() and load_team_match_stats() when match_id="angel-city-fc-vs-chicago-red-stars-2023-06-05"

The data technically exists, but it's in angel-city-fc-vs-chicago-red-stars-2023-06-04.csv
This is probably a slip up because the original match date was moved, and it's easy enough to work around, but just wanted to make you aware

**Comment by adror1** [comment]
This is stemming from the same issue as #10 and it's due to the rescheduled matches. I need to think about how to solve this, but will put it at the top of my to do list. Thanks for raising it!

**Comment by lvanden** [comment]
Data has been updated and this is resolved.
```
match_id <- "angel-city-fc-vs-chicago-red-stars-2023-06-05"
team <- load_team_match_stats(match_id = match_id) 
player <- load_player_match_stats(match_id = match_id) 

# Verify match table only has one date for this match
> load_matches() |>
+   dplyr::filter(grepl("angel-city-fc-vs-chicago-red-stars-2023-06", match_id)) |> 
+   dplyr::glimpse()
Rows: 1                                                                                                                    
Columns: 15
$ match_id           <chr> "angel-city-fc-vs-chicago-red-stars-2023-06-05"
$ home_team_id       <dbl> 15
$ away_team_id       <dbl> 2
$ kickoff            <dttm> 2023-06-05 22:00:00
$ time               <time> 22:00:00
$ stadium            <chr> "BMO Stadium"
$ city               <chr> "Los Angeles, California"
$ year               <dbl> 2023
$ season             <chr> "2023"
$ home_team_score    <dbl> 1
$ away_team_score    <dbl> 2
$ home_penalty_score <dbl> 0
$ away_penalty_score <dbl> 0
$ won_on_penalties   <lgl> FALSE
$ last_updated       <date> 2024-04-04
